package crinkle;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.UIManager;


/**
 *
 * @author ToanHo
 */
public class PlaybackMode extends javax.swing.JFrame {

	private javax.swing.JButton btnForward;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRewind;
    private javax.swing.JButton btnSnapshot;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JPanel pnlPlayback; // contain pnlPlaybackTop, Middle, Bottom
    private javax.swing.JPanel pnlViewer;
    private javax.swing.JPanel pnlLeft; // contain pnlPlayback;
    private javax.swing.JPanel pnlRight; // contain pnlViewer;
    private JPanel pnlPlaybackTop;
	private JPanel pnlPlaybackMiddle;
	private JPanel pnlPlaybackBottom;
	
    private LaunchMode launchMode;
	

    /**
     * Creates new form PlaybackMode
     */
    public PlaybackMode() {
        initComponents();
    }

    public PlaybackMode(LaunchMode launchMode) {
        initComponents();
        this.launchMode = launchMode;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    	
        pnlViewer = new javax.swing.JPanel();
        pnlPlayback = new javax.swing.JPanel();
        btnRewind = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnForward = new javax.swing.JButton();
        lblTimer = new javax.swing.JLabel();
        btnSnapshot = new javax.swing.JButton();
        pnlLeft = new javax.swing.JPanel();
        pnlRight = new javax.swing.JPanel();
        pnlPlaybackTop = new javax.swing.JPanel();
        pnlPlaybackMiddle = new javax.swing.JPanel();
        pnlPlaybackBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crinkle Viewer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnlViewer.setBorder(BorderFactory.createTitledBorder("Viewer"));
        //pnlViewer.setPreferredSize(new java.awt.Dimension(750, 705));

        GroupLayout pnlViewerLayout = new GroupLayout(pnlViewer);
        pnlViewer.setLayout(pnlViewerLayout);
        pnlViewerLayout.setHorizontalGroup(
            pnlViewerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        pnlViewerLayout.setVerticalGroup(
            pnlViewerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );

        pnlPlayback.setBorder(BorderFactory.createTitledBorder("Playback"));
        pnlPlayback.setPreferredSize(new java.awt.Dimension(210, 150));

        btnRewind.setIcon(new ImageIcon(getClass().getResource("/icons/1427489580_backward-40.png"))); // NOI18N
        btnRewind.setPreferredSize(new java.awt.Dimension(40, 40));

        btnPlay.setIcon(new ImageIcon(getClass().getResource("/icons/1427489511_icon-play-128.png"))); // NOI18N
        btnPlay.setPreferredSize(new java.awt.Dimension(50, 40));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnForward.setIcon(new ImageIcon(getClass().getResource("/icons/1427489580_fast_forward_128.png"))); // NOI18N
        btnForward.setPreferredSize(new java.awt.Dimension(40, 40));

        lblTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer.setText("00:00:00");
        lblTimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTimer.setPreferredSize(new java.awt.Dimension(175, 16));

        btnSnapshot.setIcon(new ImageIcon(getClass().getResource("/icons/1427962660_camera_-30.png"))); // NOI18N
        btnSnapshot.setPreferredSize(new java.awt.Dimension(40, 40));
        
        pnlLeft.setPreferredSize(new Dimension(220, 150));
        
        pnlPlaybackTop.setPreferredSize(new Dimension(190, 50));
        pnlPlaybackMiddle.setPreferredSize(new Dimension(190, 20));
        pnlPlaybackBottom.setPreferredSize(new Dimension(190, 50));
        
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(pnlLeft, BorderLayout.LINE_START);
        getContentPane().add(pnlRight, BorderLayout.CENTER);
        
        pnlLeft.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        pnlLeft.add(pnlPlayback);
        pnlRight.setLayout(new BorderLayout());
        pnlRight.add(pnlViewer);
        
        pnlPlayback.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        pnlPlayback.add(pnlPlaybackTop);
        pnlPlayback.add(pnlPlaybackMiddle);
        pnlPlayback.add(pnlPlaybackBottom);
        
        pnlPlaybackTop.setLayout(new FlowLayout(FlowLayout.RIGHT, 10, 0));
        pnlPlaybackTop.add(btnSnapshot);
        
        pnlPlaybackMiddle.add(lblTimer);
        
        pnlPlaybackBottom.setLayout(new FlowLayout(FlowLayout.CENTER, 15, 5));
        pnlPlaybackBottom.add(btnRewind);
        pnlPlaybackBottom.add(btnPlay);
        pnlPlaybackBottom.add(btnForward);

        setSize(960, 720);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, 0);
        
        validate();

    }
    

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        btnPlay.setIcon(new ImageIcon(getClass().getResource("/icons/1427489556_icon-pause-40.png")));
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {
        // TODO add your handling code here:
        launchMode.setVisible(true);
    }

}
