package data;

import java.util.ArrayList;
import java.util.List;

public class MovementData {
	private List<SensorReading> sensorData;
	
	/** Constructor with file name generated by hardware **/
	public MovementData(String fileName) {
		this.sensorData = buildMovementData(fileName);
	}
	
	/** Read data from sample file generated by hardware **/
	private List<SensorReading> buildMovementData(String fileName) {
		List<SensorReading> result = new ArrayList<SensorReading>();
		//TODO
		return result;
	}
	
	public boolean validate() {
		//TODO Miya
		
		return true;
	}
	
	public void next() {
		//TODO  Miya
	}
	
	public void previous() {
		//TODO Miya
	}

	public List<SensorReading> getSensorData() {
		return sensorData;
	}

	public void setSensorData(List<SensorReading> sensorData) {
		this.sensorData = sensorData;
	}
}
